//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployerPartners.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_AppUsersVersion
    {
        public string UserName { get; set; }
        public string Version { get; set; }
        public Nullable<System.DateTime> OpenTimestamp { get; set; }
        public Nullable<System.DateTime> LastUpdateTimestamp { get; set; }
    }
}
