//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployerPartners.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class ECD_EmpContactsDetailsUNP_GAK2016
    {
        public string SPbGU { get; set; }
        public string Chairman { get; set; }
        public string Title { get; set; }
        public string Name { get; set; }
        public string FirstNameEng { get; set; }
        public string LastNameEng { get; set; }
        public string Position { get; set; }
        public string PositionEng { get; set; }
        public string AAP { get; set; }
        public string AAPEng { get; set; }
        public string OrgName { get; set; }
        public string OrgNameEng { get; set; }
        public string CountryName { get; set; }
        public string CountryNameEng { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public int Id { get; set; }
        public string UNP { get; set; }
    }
}
