//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployerPartners.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class ECD_OrganizationPersonOrgName
    {
        public int PartnerPersonId { get; set; }
        public Nullable<int> OrganizationId { get; set; }
        public string OrgName { get; set; }
    }
}
