//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployerPartners.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPLog
    {
        public int Id { get; set; }
        public string ActionName { get; set; }
        public string ActionValue { get; set; }
        public Nullable<System.DateTime> ActionTime { get; set; }
        public string ActionUser { get; set; }
        public string ActionName1 { get; set; }
        public string ActionValue1 { get; set; }
        public Nullable<System.DateTime> ActionTime1 { get; set; }
        public string Version { get; set; }
    }
}
