//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployerPartners.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class ext_GAK_2017
    {
        public string ExamVKR { get; set; }
        public string GAKNumber { get; set; }
        public string DateTimeMeeting { get; set; }
        public string ObrazProgramNumber { get; set; }
        public string ObrazProgram { get; set; }
        public string UNP { get; set; }
        public string External { get; set; }
        public string Chairman { get; set; }
        public string Name { get; set; }
        public string NameInitials { get; set; }
        public string NameEng { get; set; }
        public string NameInitialsEng { get; set; }
        public string Degree { get; set; }
        public string DegreeEng { get; set; }
        public string Rank { get; set; }
        public string RankEng { get; set; }
        public string RankHonorary { get; set; }
        public string RankHonoraryEng { get; set; }
        public string RankState { get; set; }
        public string RankStateEng { get; set; }
        public string Country { get; set; }
        public string Email { get; set; }
        public string OrgPosition { get; set; }
        public string OrgPositionEng { get; set; }
        public Nullable<int> PartnerId { get; set; }
        public string Account { get; set; }
        public string Title { get; set; }
        public Nullable<bool> IsAbsent { get; set; }
        public string TitleEng { get; set; }
        public Nullable<int> NPR_Tabnum { get; set; }
    }
}
