//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployerPartners.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class extPartnerPersonRubric
    {
        public Nullable<int> PartnerPersonId { get; set; }
        public string Рубрика { get; set; }
        public string Год { get; set; }
        public string Уровень { get; set; }
        public string Направление { get; set; }
        public string Тип_программы { get; set; }
        public string Квалификация { get; set; }
        public int RubricTypeId { get; set; }
        public Nullable<int> Sorting { get; set; }
        public int ObjectId { get; set; }
        public string ObjectCard { get; set; }
    }
}
