//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployerPartners.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class GAK_Number_archive
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GAK_Number_archive()
        {
            this.GAK_MemberNPR_archive = new HashSet<GAK_MemberNPR_archive>();
            this.GAK_MemberPP_archive = new HashSet<GAK_MemberPP_archive>();
        }
    
        public int Id { get; set; }
        public string Action { get; set; }
        public int GAK_NumberId { get; set; }
        public int GAKId { get; set; }
        public int ObrazProgramId { get; set; }
        public string GAKNumber { get; set; }
        public string GAKNumberOld { get; set; }
        public int ExamVKRId { get; set; }
        public Nullable<int> GAK_LP_PersonId { get; set; }
        public Nullable<int> PartnerPersonId { get; set; }
        public string Coordinator { get; set; }
        public string Address { get; set; }
        public string Auditorium { get; set; }
        public Nullable<System.DateTime> DateTimeMeeting { get; set; }
        public string Comment { get; set; }
        public Nullable<bool> Freeze { get; set; }
        public Nullable<bool> ToOrder { get; set; }
        public Nullable<bool> InOrder { get; set; }
        public string OrderNumber { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<bool> OrderDop { get; set; }
        public string AuthorUpdated { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public string Author { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string AuthorLog { get; set; }
        public Nullable<System.DateTime> DateCreatedLog { get; set; }
    
        public virtual GAK GAK { get; set; }
        public virtual GAK_ExamVKR GAK_ExamVKR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GAK_MemberNPR_archive> GAK_MemberNPR_archive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GAK_MemberPP_archive> GAK_MemberPP_archive { get; set; }
        public virtual GAK_Number GAK_Number { get; set; }
        public virtual ObrazProgram ObrazProgram { get; set; }
        public virtual PartnerPerson PartnerPerson { get; set; }
    }
}
