//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployerPartners.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class GAK_StatLP_UNP_ItogExtPercent
    {
        public string Faculty { get; set; }
        public Nullable<int> OPquan { get; set; }
        public Nullable<int> GAKquan { get; set; }
        public Nullable<int> GAKExamquan { get; set; }
        public Nullable<int> GAKVKRquan { get; set; }
        public Nullable<int> GAKItogquan { get; set; }
        public Nullable<int> MemberSPbGU { get; set; }
        public Nullable<int> MemberPP { get; set; }
        public Nullable<int> MemberChairman { get; set; }
        public string MemberSPbGUPercent { get; set; }
        public string MemberPPPercent { get; set; }
    }
}
