//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployerPartners.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class GAK_Adapter
    {
        public int Id { get; set; }
        public string OPNumber { get; set; }
        public string LPCode { get; set; }
        public string RegNumWP { get; set; }
        public string UNP { get; set; }
        public string Comment { get; set; }
    }
}
