//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployerPartners.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class GAK_StatOP
    {
        public int GAK_NumberId { get; set; }
        public string StudyLevel { get; set; }
        public int ExamVKRId { get; set; }
        public string ExamVKR { get; set; }
        public int ObrazProgramId { get; set; }
        public int StudyLevelId { get; set; }
    }
}
