//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployerPartners.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class GAK_StatChairmanPPNPR_LP_ItogExtPercent
    {
        public int StudyLevelId { get; set; }
        public string StudyLevel { get; set; }
        public int LicenseProgramId { get; set; }
        public string LicenseProgram { get; set; }
        public string LPCode { get; set; }
        public Nullable<int> MemberSPbGU { get; set; }
        public Nullable<int> MemberPP { get; set; }
        public Nullable<int> MemberChairman { get; set; }
        public Nullable<int> MemberExt { get; set; }
        public string MemberSPbGUPercent { get; set; }
        public string MemberPPPercent { get; set; }
    }
}
