//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployerPartners.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class GAK_StatChairmanPPNPR_Itog2
    {
        public int StudyLevelId { get; set; }
        public string StudyLevel { get; set; }
        public Nullable<int> MemberSPbGU { get; set; }
        public Nullable<int> MemberPP { get; set; }
        public Nullable<int> MemberChairman { get; set; }
        public Nullable<int> MemberExamSPbGU { get; set; }
        public Nullable<int> MemberExamPP { get; set; }
        public Nullable<int> MemberExamChairman { get; set; }
        public Nullable<int> MemberVKRSPbGU { get; set; }
        public Nullable<int> MemberVKRPP { get; set; }
        public Nullable<int> MemberVKRChairman { get; set; }
        public Nullable<int> MemberItogSPbGU { get; set; }
        public Nullable<int> MemberItogPP { get; set; }
        public Nullable<int> MemberItogChairman { get; set; }
    }
}
