//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployerPartners.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class InboxMessageFile
    {
        public int Id { get; set; }
        public int InboxMessageId { get; set; }
        public byte[] FileData { get; set; }
        public string FileName { get; set; }
    
        public virtual InboxMessage InboxMessage { get; set; }
    }
}
