//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployerPartners.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class InboxMessage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InboxMessage()
        {
            this.InboxMessageFile = new HashSet<InboxMessageFile>();
        }
    
        public int Id { get; set; }
        public string Theme { get; set; }
        public string Text { get; set; }
        public int OrganizationId { get; set; }
        public string Author { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Organization Organization { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InboxMessageFile> InboxMessageFile { get; set; }
    }
}
