//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployerPartners.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class LicenseInLicenseProgram
    {
        public System.Guid Id { get; set; }
        public int LicenseProgramId { get; set; }
        public int LicenseId { get; set; }
        public string ApplicationNum { get; set; }
        public string PositionNum { get; set; }
        public string PartNum { get; set; }
        public bool IsOpen { get; set; }
        public string Holder { get; set; }
        public string Author { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateStart { get; set; }
        public Nullable<System.DateTime> DateFinish { get; set; }
    
        public virtual License License { get; set; }
        public virtual LicenseProgram LicenseProgram { get; set; }
    }
}
