//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployerPartners.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class OECD
    {
        public int Id { get; set; }
        public string Code1 { get; set; }
        public string NameEng1 { get; set; }
        public string NameRus1 { get; set; }
        public string Code2 { get; set; }
        public string NameEng2 { get; set; }
        public string NameRus2 { get; set; }
        public string Code3 { get; set; }
        public string NameEng3 { get; set; }
        public string NameRus3 { get; set; }
        public string Author { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    }
}
