//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployerPartners.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrganizationOkved
    {
        public int Id { get; set; }
        public int OrganizationId { get; set; }
        public string Okved { get; set; }
        public int OkvedTypeId { get; set; }
        public string OkvedName { get; set; }
        public string Author { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    
        public virtual OkvedType OkvedType { get; set; }
        public virtual Organization Organization { get; set; }
    }
}
