//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployerPartners.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrganizationBuf
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string MiddleName { get; set; }
        public string ShortName { get; set; }
        public string NameEng { get; set; }
        public string ShortNameEng { get; set; }
        public Nullable<System.DateTime> NameDate { get; set; }
        public string Source { get; set; }
        public Nullable<bool> SourceCharter { get; set; }
        public Nullable<bool> SourceEGRUL { get; set; }
        public Nullable<bool> SourceSite { get; set; }
        public Nullable<bool> CardChecked { get; set; }
        public Nullable<bool> IsActual { get; set; }
        public string Description { get; set; }
        public Nullable<bool> SPbGU { get; set; }
        public string OECD { get; set; }
        public string Okved { get; set; }
        public string OkvedDop { get; set; }
        public Nullable<int> OwnershipTypeId { get; set; }
        public Nullable<int> ActivityGoalId { get; set; }
        public Nullable<int> NationalAffiliationId { get; set; }
        public Nullable<int> ActivityAreaId { get; set; }
        public Nullable<int> ActivityAreaProfessionalId { get; set; }
        public string Contact { get; set; }
        public string INN { get; set; }
        public string OGRN { get; set; }
        public Nullable<System.DateTime> OGRNDate { get; set; }
        public Nullable<System.DateTime> CloseDate { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Mobiles { get; set; }
        public string Fax { get; set; }
        public string WebSite { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> RegionId { get; set; }
        public string CodeKLADR { get; set; }
        public string Code { get; set; }
        public string City { get; set; }
        public string Street { get; set; }
        public string House { get; set; }
        public string Apartment { get; set; }
        public string Address { get; set; }
        public string Comment { get; set; }
        public string VKR { get; set; }
        public string FacVKR { get; set; }
        public string GAK { get; set; }
        public string FacGAK { get; set; }
        public string Author { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.Guid rowguid { get; set; }
        public Nullable<int> ImportAccessCode { get; set; }
        public Nullable<int> OrganizationId { get; set; }
    }
}
