//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployerPartners.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnerPersonOrganizationLetter
    {
        public int Id { get; set; }
        public int PartnerPersonId { get; set; }
        public int OrganizationId { get; set; }
        public string Author { get; set; }
        public bool IsSend { get; set; }
        public System.DateTime Timestamp { get; set; }
        public string IsSendAuthor { get; set; }
        public Nullable<System.DateTime> IsSendTimestamp { get; set; }
    }
}
