//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployerPartners.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnerPersonOrgPosition
    {
        public int Id { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string SecondName { get; set; }
        public string Name { get; set; }
        public string NameInitials { get; set; }
        public Nullable<int> PartnerPersonPrefixId { get; set; }
        public string LastNameEng { get; set; }
        public string FirstNameEng { get; set; }
        public string SecondNameEng { get; set; }
        public string NameEng { get; set; }
        public string NameInitialsEng { get; set; }
        public string Title { get; set; }
        public string TitleEng { get; set; }
        public string Account { get; set; }
        public Nullable<int> DegreeId { get; set; }
        public Nullable<int> Degree2Id { get; set; }
        public Nullable<int> RankId { get; set; }
        public Nullable<int> Rank2Id { get; set; }
        public Nullable<int> RankHonoraryId { get; set; }
        public Nullable<int> RankHonorary2Id { get; set; }
        public Nullable<int> RankStateId { get; set; }
        public Nullable<int> RankState2Id { get; set; }
        public Nullable<int> ActivityAreaId { get; set; }
        public Nullable<bool> IsSPbGUGraduate { get; set; }
        public Nullable<int> SPbGUGraduateYear { get; set; }
        public Nullable<bool> AlumniAssociation { get; set; }
        public Nullable<bool> IsGAK { get; set; }
        public Nullable<bool> IsGAKChairman { get; set; }
        public Nullable<bool> IsGAK2016 { get; set; }
        public Nullable<bool> IsGAKChairman2016 { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Mobiles { get; set; }
        public string WebSite { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> RegionId { get; set; }
        public string CodeKLADR { get; set; }
        public string Code { get; set; }
        public string City { get; set; }
        public string Street { get; set; }
        public string House { get; set; }
        public string Comment { get; set; }
        public string Author { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.Guid rowguid { get; set; }
        public string OrgPosition { get; set; }
        public string DegreeName { get; set; }
        public string RankName { get; set; }
    }
}
