//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployerPartners.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class PracticePlan
    {
        public int Id { get; set; }
        public System.Guid StudyPlanId { get; set; }
        public string StudyPlanNumber { get; set; }
        public int DisciplineId { get; set; }
        public string DisciplineNumber { get; set; }
        public string DisciplineName { get; set; }
        public Nullable<int> ModuleNameId { get; set; }
        public string ModuleName { get; set; }
        public Nullable<int> EducYear { get; set; }
        public Nullable<int> ModuleNameIntValue { get; set; }
        public Nullable<short> StudyCourse { get; set; }
        public int ObrazProgramId { get; set; }
        public int StudyFormId { get; set; }
        public Nullable<int> LicenseProgramId { get; set; }
        public Nullable<int> FacultyId { get; set; }
        public Nullable<int> LicenseId { get; set; }
        public Nullable<int> StudyLevelId { get; set; }
        public string ObrazProgramCrypt { get; set; }
        public Nullable<System.Guid> ObrazProgramInYearId { get; set; }
        public Nullable<int> TrajectoryId { get; set; }
        public Nullable<int> RealizationVariantId { get; set; }
        public string RealizationVariantName { get; set; }
        public string TrajectoryName { get; set; }
        public string RealizationVariantAcronymEng { get; set; }
        public string ProfileName { get; set; }
    }
}
