//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployerPartners.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class PracticeLP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PracticeLP()
        {
            this.PracticeLPOrganization = new HashSet<PracticeLPOrganization>();
            this.PracticeLPStudent = new HashSet<PracticeLPStudent>();
            this.PracticeLPFile = new HashSet<PracticeLPFile>();
            this.PracticeLPOP = new HashSet<PracticeLPOP>();
        }
    
        public int Id { get; set; }
        public int PracticeId { get; set; }
        public int LicenseProgramId { get; set; }
        public Nullable<int> PracticeTypeId { get; set; }
        public Nullable<System.DateTime> DateStart { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public string OrderDoc { get; set; }
        public string OrderNumber { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string OrderAuthor { get; set; }
        public string InstructionDoc { get; set; }
        public string InstructionNumber { get; set; }
        public Nullable<System.DateTime> InstructionDate { get; set; }
        public string InstructionAuthor { get; set; }
        public string Supervisor { get; set; }
        public string AdvanceHolder { get; set; }
        public string Comment { get; set; }
        public string Author { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<bool> OutSPb { get; set; }
        public Nullable<System.Guid> StudyPlanId { get; set; }
        public string StudyPlanNumber { get; set; }
        public Nullable<int> DisciplineId { get; set; }
        public string DisciplineNumber { get; set; }
        public string DisciplineName { get; set; }
        public Nullable<int> ModuleNameId { get; set; }
        public string ModuleName { get; set; }
        public Nullable<int> EducYear { get; set; }
        public Nullable<int> ModuleNameIntValue { get; set; }
        public Nullable<short> StudyCourse { get; set; }
        public Nullable<int> ObrazProgramId { get; set; }
        public Nullable<int> StudyFormId { get; set; }
        public Nullable<int> FacultyId { get; set; }
        public Nullable<int> LicenseId { get; set; }
        public Nullable<int> StudyLevelId { get; set; }
        public string ObrazProgramCrypt { get; set; }
        public Nullable<System.Guid> ObrazProgramInYearId { get; set; }
        public Nullable<int> TrajectoryId { get; set; }
        public Nullable<int> RealizationVariantId { get; set; }
        public string RealizationVariantName { get; set; }
        public string TrajectoryName { get; set; }
        public string RealizationVariantAcronymEng { get; set; }
        public string ProfileName { get; set; }
    
        public virtual LicenseProgram LicenseProgram { get; set; }
        public virtual Practice Practice { get; set; }
        public virtual PracticeType PracticeType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PracticeLPOrganization> PracticeLPOrganization { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PracticeLPStudent> PracticeLPStudent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PracticeLPFile> PracticeLPFile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PracticeLPOP> PracticeLPOP { get; set; }
    }
}
