//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployerPartners.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class PracticeLPOP
    {
        public int Id { get; set; }
        public int PracticeLPId { get; set; }
        public int ObrazProgramId { get; set; }
        public int ObrazProgramInYearId { get; set; }
        public string Comment { get; set; }
        public string Author { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    
        public virtual ObrazProgram ObrazProgram { get; set; }
        public virtual ObrazProgramInYear ObrazProgramInYear { get; set; }
        public virtual PracticeLP PracticeLP { get; set; }
    }
}
