//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployerPartners.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgramMode
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProgramMode()
        {
            this.ObrazProgram = new HashSet<ObrazProgram>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string NameEng { get; set; }
        public string Acronym { get; set; }
        public string EntranceRequest { get; set; }
        public string EntranceRequestEng { get; set; }
        public Nullable<int> ProgramTypeId { get; set; }
        public Nullable<int> StudyLevelId { get; set; }
        public bool IsOpen { get; set; }
        public string Holder { get; set; }
        public bool IsUseEng { get; set; }
        public bool IsUseForPrint { get; set; }
        public string Author { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ObrazProgram> ObrazProgram { get; set; }
        public virtual ProgramType ProgramType { get; set; }
        public virtual StudyLevel StudyLevel { get; set; }
    }
}
