//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployerPartners.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAP_NPR
    {
        public string Persnum { get; set; }
        public string Tabnum { get; set; }
        public string Lastname { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Birthdate { get; set; }
        public string Positionname { get; set; }
        public string OrgId { get; set; }
        public string OrgUpId { get; set; }
        public string ShortName { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public string UsridAd { get; set; }
        public string Pkateg { get; set; }
        public string Pgroup { get; set; }
        public string Telnr { get; set; }
        public string Addressfact { get; set; }
        public string Titel { get; set; }
        public string Titl2 { get; set; }
        public string Civil { get; set; }
        public Nullable<System.DateTime> TIMESTAMP { get; set; }
        public string Faculty { get; set; }
        public string Position { get; set; }
        public string Degree { get; set; }
    }
}
