//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployerPartners.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAP_ORGSTRUCTURE
    {
        public string OrgId { get; set; }
        public string OrgUpId { get; set; }
        public string ShortName { get; set; }
        public string FullName { get; set; }
        public string Begda { get; set; }
        public string Endda { get; set; }
        public Nullable<System.DateTime> TIMESTAMP { get; set; }
    }
}
