//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployerPartners.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAP_POSITIONS
    {
        public string PosId { get; set; }
        public string OrgId { get; set; }
        public string Name { get; set; }
        public string FullName { get; set; }
        public string DateFrom { get; set; }
        public string DateTo { get; set; }
        public string Quantity { get; set; }
        public Nullable<System.DateTime> TIMESTAMP { get; set; }
    }
}
