//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployerPartners.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SOP()
        {
            this.SOP_Conference = new HashSet<SOP_Conference>();
            this.SOP_Members_NPR = new HashSet<SOP_Members_NPR>();
            this.SOP_Members_PartnerPerson = new HashSet<SOP_Members_PartnerPerson>();
            this.SOP_ObrazProgram = new HashSet<SOP_ObrazProgram>();
            this.SOP_OrganizationMail = new HashSet<SOP_OrganizationMail>();
        }
    
        public int Id { get; set; }
        public string Author { get; set; }
        public System.DateTime Timestamp { get; set; }
        public string AuthorUpdate { get; set; }
        public Nullable<System.DateTime> TimestampUpdate { get; set; }
        public string Name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOP_Conference> SOP_Conference { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOP_Members_NPR> SOP_Members_NPR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOP_Members_PartnerPerson> SOP_Members_PartnerPerson { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOP_ObrazProgram> SOP_ObrazProgram { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOP_OrganizationMail> SOP_OrganizationMail { get; set; }
    }
}
