//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployerPartners.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOP_Members_PartnerPerson
    {
        public int Id { get; set; }
        public int SOPId { get; set; }
        public int PartnerPersonId { get; set; }
        public string Author { get; set; }
        public System.DateTime Timestamp { get; set; }
        public Nullable<int> PositionId { get; set; }
    
        public virtual SOP SOP { get; set; }
    }
}
