//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployerPartners.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOP_ConferenceMembers_NPR
    {
        public int Id { get; set; }
        public int SOPConferenceId { get; set; }
        public string Author { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
        public string Tabnum { get; set; }
    
        public virtual SOP_Conference SOP_Conference { get; set; }
    }
}
