//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployerPartners.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOP_Conference_Questions_Files
    {
        public System.Guid Id { get; set; }
        public int SOPConferenceQuestionId { get; set; }
        public string FileName { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
        public string Author { get; set; }
    
        public virtual SOP_Conference_Questions SOP_Conference_Questions { get; set; }
    }
}
