//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployerPartners.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentDVZ
    {
        public int Id { get; set; }
        public Nullable<int> StudDataId { get; set; }
        public string FIO { get; set; }
        public string Surname { get; set; }
        public string FirstName { get; set; }
        public string SecondName { get; set; }
        public string Course { get; set; }
        public string WorkPlan { get; set; }
        public string RegNomWP { get; set; }
        public string Department { get; set; }
        public string StudyBasis { get; set; }
        public string DegreeName { get; set; }
        public string Accout { get; set; }
        public string MailBox { get; set; }
        public string FacultyName { get; set; }
        public string DR { get; set; }
        public string PersNumber { get; set; }
        public string SpecNumber { get; set; }
        public string SpecName { get; set; }
        public string StatusName { get; set; }
        public string StudyingName { get; set; }
        public Nullable<System.DateTime> TIMESTAMP { get; set; }
        public Nullable<int> Sex { get; set; }
    }
}
