//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployerPartners.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudyPlanData
    {
        public int Id { get; set; }
        public string StudyPlanNumber { get; set; }
        public string PlanYear { get; set; }
        public Nullable<int> ObrazProgramId { get; set; }
        public Nullable<int> LicenseProgramId { get; set; }
        public Nullable<int> FacultyId { get; set; }
        public string ObrazProgramCrypt { get; set; }
        public Nullable<System.Guid> ObrazProgramInYearId { get; set; }
        public Nullable<System.DateTime> DateFinish { get; set; }
    }
}
