//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployerPartners.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teacher
    {
        public int Id { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string SecondName { get; set; }
        public int AcademicTitleId { get; set; }
        public int DegreeId { get; set; }
        public string Position { get; set; }
        public string MainWorkName { get; set; }
        public decimal Employment { get; set; }
        public int EmploymentTypeId { get; set; }
        public int DivisionId { get; set; }
        public int ChairId { get; set; }
        public bool IsOpen { get; set; }
        public string Holder { get; set; }
        public Nullable<int> WorkInSPBUType { get; set; }
        public string Author { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    }
}
