//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployerPartners.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class VKR_OrderSource
    {
        public int Id { get; set; }
        public string GraduateYear { get; set; }
        public Nullable<int> FacultyId { get; set; }
        public string FacultyName { get; set; }
        public Nullable<int> StudyLevelId { get; set; }
        public string Basis { get; set; }
        public string ChairmanForOrder { get; set; }
        public string ChairmanForSend { get; set; }
        public string UOPForSend { get; set; }
        public string UUForSend { get; set; }
        public string Comment { get; set; }
        public string Author { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    }
}
