//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployerPartners.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class VKR_Themes_NPR
    {
        public int Id { get; set; }
        public int VKRThemeId { get; set; }
        public string Tabnum { get; set; }
        public string NPR_SecondName { get; set; }
        public string NPR_Position { get; set; }
        public string NPR_Degree { get; set; }
        public string NPR_Rank { get; set; }
        public string NPR_Account { get; set; }
        public string NPR_Chair { get; set; }
        public string NPR_Surname { get; set; }
        public string NPR_Name { get; set; }
    
        public virtual VKR_Themes VKR_Themes { get; set; }
    }
}
