//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployerPartners.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class VKR_ThemesStudentOrder
    {
        public int Id { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> VKRId { get; set; }
        public string GraduateYear { get; set; }
        public Nullable<int> StudDataId { get; set; }
        public string FIO { get; set; }
        public string Surname { get; set; }
        public string FirstName { get; set; }
        public string SecondName { get; set; }
        public string FIO_old { get; set; }
        public string Surname_old { get; set; }
        public string FirstName_old { get; set; }
        public string SecondName_old { get; set; }
        public string Course { get; set; }
        public string WorkPlan { get; set; }
        public string RegNomWP { get; set; }
        public string Department { get; set; }
        public string StudyBasis { get; set; }
        public string DegreeName { get; set; }
        public string Accout { get; set; }
        public string MailBox { get; set; }
        public string FacultyName { get; set; }
        public string DR { get; set; }
        public string PersNumber { get; set; }
        public string SpecNumber { get; set; }
        public string SpecName { get; set; }
        public string StatusName { get; set; }
        public string StudyingName { get; set; }
        public string StudyPlanNumber { get; set; }
        public string PlanYear { get; set; }
        public Nullable<int> ObrazProgramId { get; set; }
        public Nullable<int> LicenseProgramId { get; set; }
        public Nullable<int> FacultyId { get; set; }
        public string ObrazProgramCrypt { get; set; }
        public Nullable<System.Guid> ObrazProgramInYearId { get; set; }
        public string NPR_FIO { get; set; }
        public string NPR_Position { get; set; }
        public string NPR_Degree { get; set; }
        public string NPR_Rank { get; set; }
        public string NPR_Account { get; set; }
        public string NPR_Chair { get; set; }
        public string NPR_Faculty { get; set; }
        public Nullable<bool> NPR_set { get; set; }
        public string NPR_FIO_Student { get; set; }
        public string NPR_Position_Student { get; set; }
        public string NPR_Degree_Student { get; set; }
        public string NPR_Rank_Student { get; set; }
        public string NPR_Account_Student { get; set; }
        public string NPR_Chair_Student { get; set; }
        public string NPR_Faculty_Student { get; set; }
        public Nullable<bool> NPR_Student_set { get; set; }
        public string NPR_FIO_Final { get; set; }
        public string NPR_Position_Final { get; set; }
        public string NPR_Degree_Final { get; set; }
        public string NPR_Rank_Final { get; set; }
        public string NPR_Account_Final { get; set; }
        public string NPR_Chair_Final { get; set; }
        public string NPR_Faculty_Final { get; set; }
        public Nullable<bool> NPR_Final_set { get; set; }
        public string NPR_Changed_Persnum { get; set; }
        public string NPR_Changed_Tabnum { get; set; }
        public string NPR_FIO_Changed { get; set; }
        public string NPR_Position_Changed { get; set; }
        public string NPR_Degree_Changed { get; set; }
        public string NPR_Rank_Changed { get; set; }
        public string NPR_Account_Changed { get; set; }
        public string NPR_Chair_Changed { get; set; }
        public string NPR_Faculty_Changed { get; set; }
        public string NPR_Changed_Persnum2 { get; set; }
        public string NPR_Changed_Tabnum2 { get; set; }
        public string NPR_FIO_Changed2 { get; set; }
        public string NPR_Position_Changed2 { get; set; }
        public string NPR_Degree_Changed2 { get; set; }
        public string NPR_Rank_Changed2 { get; set; }
        public string NPR_Account_Changed2 { get; set; }
        public string NPR_Chair_Changed2 { get; set; }
        public string NPR_Faculty_Changed2 { get; set; }
        public string VKRName { get; set; }
        public string VKRNameEng { get; set; }
        public Nullable<bool> VKRName_set { get; set; }
        public Nullable<bool> VKRNameEng_set { get; set; }
        public string VKRName_Student { get; set; }
        public string VKRNameEng_Student { get; set; }
        public Nullable<bool> VKRName_Student_set { get; set; }
        public Nullable<bool> VKRNameEng_Student_set { get; set; }
        public string Priority { get; set; }
        public string VKRName_Final { get; set; }
        public string VKRNameEng_Final { get; set; }
        public Nullable<bool> VKRName_Final_set { get; set; }
        public Nullable<bool> VKRNameEng_Final_set { get; set; }
        public string VKRName_Changed { get; set; }
        public string VKRNameEng_Changed { get; set; }
        public string VKRName_ChangedDoc { get; set; }
        public string VKRName_Changed2 { get; set; }
        public string VKRNameEng_Changed2 { get; set; }
        public string VKRName_ChangedDoc2 { get; set; }
        public Nullable<int> OrganizationId { get; set; }
        public string OrganizationName { get; set; }
        public string OrganizationDocument { get; set; }
        public Nullable<int> OrganizationId2 { get; set; }
        public string OrganizationName2 { get; set; }
        public string OrganizationDocument2 { get; set; }
        public Nullable<int> OrganizationId3 { get; set; }
        public string OrganizationName3 { get; set; }
        public string OrganizationDocument3 { get; set; }
        public Nullable<int> OrganizationId_Changed2 { get; set; }
        public string OrganizationName_Changed2 { get; set; }
        public string OrganizationDocument_Changed2 { get; set; }
        public string Review_NPR_Persnum { get; set; }
        public string Review_NPR_Tabnum { get; set; }
        public string Review_NPR_FIO { get; set; }
        public string Review_NPR_Position { get; set; }
        public string Review_NPR_Degree { get; set; }
        public string Review_NPR_Rank { get; set; }
        public string Review_NPR_Account { get; set; }
        public string Review_NPR_Chair { get; set; }
        public string Review_NPR_Faculty { get; set; }
        public string Review_NPR_Persnum2 { get; set; }
        public string Review_NPR_Tabnum2 { get; set; }
        public string Review_NPR_FIO2 { get; set; }
        public string Review_NPR_Position2 { get; set; }
        public string Review_NPR_Degree2 { get; set; }
        public string Review_NPR_Rank2 { get; set; }
        public string Review_NPR_Account2 { get; set; }
        public string Review_NPR_Chair2 { get; set; }
        public string Review_NPR_Faculty2 { get; set; }
        public Nullable<int> Review_PartnerPersonId { get; set; }
        public string Review_PP_FIO { get; set; }
        public string Review_PP_Position { get; set; }
        public string Review_PP_Degree { get; set; }
        public string Review_PP_Rank { get; set; }
        public string Review_PP_Account { get; set; }
        public string Review_PP_Subdivision { get; set; }
        public string Review_PP_Organization { get; set; }
        public string Review_PP_OrgPosition { get; set; }
        public Nullable<int> Review_PartnerPersonId2 { get; set; }
        public string Review_PP_FIO2 { get; set; }
        public string Review_PP_Position2 { get; set; }
        public string Review_PP_Degree2 { get; set; }
        public string Review_PP_Rank2 { get; set; }
        public string Review_PP_Account2 { get; set; }
        public string Review_PP_Subdivision2 { get; set; }
        public string Review_PP_Organization2 { get; set; }
        public string Review_PP_OrgPosition2 { get; set; }
        public string Review_NPR_Persnum_Changed2 { get; set; }
        public string Review_NPR_Tabnum_Changed2 { get; set; }
        public string Review_NPR_FIO_Changed2 { get; set; }
        public string Review_NPR_Position_Changed2 { get; set; }
        public string Review_NPR_Degree_Changed2 { get; set; }
        public string Review_NPR_Rank_Changed2 { get; set; }
        public string Review_NPR_Account_Changed2 { get; set; }
        public string Review_NPR_Chair_Changed2 { get; set; }
        public string Review_NPR_Faculty_Changed2 { get; set; }
        public string Review_NPR_Persnum2_Changed2 { get; set; }
        public string Review_NPR_Tabnum2_Changed2 { get; set; }
        public string Review_NPR_FIO2_Changed2 { get; set; }
        public string Review_NPR_Position2_Changed2 { get; set; }
        public string Review_NPR_Degree2_Changed2 { get; set; }
        public string Review_NPR_Rank2_Changed2 { get; set; }
        public string Review_NPR_Account2_Changed2 { get; set; }
        public string Review_NPR_Chair2_Changed2 { get; set; }
        public string Review_NPR_Faculty2_Changed2 { get; set; }
        public Nullable<int> Review_PartnerPersonId_Changed2 { get; set; }
        public string Review_PP_FIO_Changed2 { get; set; }
        public string Review_PP_Position_Changed2 { get; set; }
        public string Review_PP_Degree_Changed2 { get; set; }
        public string Review_PP_Rank_Changed2 { get; set; }
        public string Review_PP_Account_Changed2 { get; set; }
        public string Review_PP_Subdivision_Changed2 { get; set; }
        public string Review_PP_Organization_Changed2 { get; set; }
        public string Review_PP_OrgPosition_Changed2 { get; set; }
        public Nullable<int> Review_PartnerPersonId2_Changed2 { get; set; }
        public string Review_PP_FIO2_Changed2 { get; set; }
        public string Review_PP_Position2_Changed2 { get; set; }
        public string Review_PP_Degree2_Changed2 { get; set; }
        public string Review_PP_Rank2_Changed2 { get; set; }
        public string Review_PP_Account2_Changed2 { get; set; }
        public string Review_PP_Subdivision2_Changed2 { get; set; }
        public string Review_PP_Organization2_Changed2 { get; set; }
        public string Review_PP_OrgPosition2_Changed2 { get; set; }
        public Nullable<bool> Review_SPbGU { get; set; }
        public string Review_FIO_Final { get; set; }
        public string Review_Position_Final { get; set; }
        public string Review_Degree_Final { get; set; }
        public string Review_Rank_Final { get; set; }
        public string Review_Account_Final { get; set; }
        public Nullable<int> Consult_PartnerPersonId { get; set; }
        public string Consult_PP_FIO { get; set; }
        public string Consult_PP_Position { get; set; }
        public string Consult_PP_Degree { get; set; }
        public string Consult_PP_Rank { get; set; }
        public string Consult_PP_Account { get; set; }
        public string Consult_PP_Subdivision { get; set; }
        public string Consult_PP_Organization { get; set; }
        public string Comment { get; set; }
        public Nullable<bool> Freeze { get; set; }
        public Nullable<bool> ToOrder { get; set; }
        public Nullable<bool> InOrder { get; set; }
        public string OrderNumber { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<bool> OrderDop { get; set; }
        public Nullable<int> StudentNumberInOrder { get; set; }
        public Nullable<bool> FreezeReview { get; set; }
        public Nullable<bool> ToOrderReview { get; set; }
        public Nullable<bool> InOrderReview { get; set; }
        public string OrderNumberReview { get; set; }
        public Nullable<System.DateTime> OrderDateReview { get; set; }
        public Nullable<bool> OrderDopReview { get; set; }
        public Nullable<int> StudentNumberInOrderReview { get; set; }
        public string AuthorUpdated { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public string AuthorFreese { get; set; }
        public Nullable<System.DateTime> DateFreeze { get; set; }
        public string Author { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<bool> OrganizationDop_Changed2 { get; set; }
        public Nullable<bool> OrganizationNotAgreed_Changed2 { get; set; }
        public Nullable<bool> Review_NotUsePrevious_Changed2 { get; set; }
    
        public virtual Faculty Faculty { get; set; }
        public virtual LicenseProgram LicenseProgram { get; set; }
        public virtual ObrazProgram ObrazProgram { get; set; }
        public virtual Organization Organization { get; set; }
        public virtual PartnerPerson PartnerPerson { get; set; }
        public virtual PartnerPerson PartnerPerson1 { get; set; }
    }
}
