//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployerPartners.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class VKR_Themes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VKR_Themes()
        {
            this.VKR_Themes_NPR = new HashSet<VKR_Themes_NPR>();
            this.VKR_Themes_StudyPlans = new HashSet<VKR_Themes_StudyPlans>();
            this.VKR_Themes_OrderNums = new HashSet<VKR_Themes_OrderNums>();
        }
    
        public int Id { get; set; }
        public int GraduateYear { get; set; }
        public string VKRSourceKey { get; set; }
        public string DocumentNumber { get; set; }
        public string VKRName { get; set; }
        public string VKRNameEng { get; set; }
        public Nullable<int> OrganizationId { get; set; }
        public string OrganizationName { get; set; }
        public string Consult_Surname { get; set; }
        public string Consult_Name { get; set; }
        public string Consult_SecondName { get; set; }
        public string Consult_Position { get; set; }
        public string Consult_Degree { get; set; }
        public string Consult_Rank { get; set; }
        public Nullable<int> Consult_OrganizationId { get; set; }
        public string Consult_OrganizationName { get; set; }
        public string Comment { get; set; }
        public string OrderNumber { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string Author { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string RKNum { get; set; }
        public Nullable<System.DateTime> RKDate { get; set; }
        public Nullable<int> VKRThemeBankId { get; set; }
        public Nullable<bool> CommandWork { get; set; }
        public Nullable<bool> CanBeSelectedNextYear { get; set; }
        public bool EngOriginal { get; set; }
        public bool RecievedFromGAKMember { get; set; }
        public Nullable<int> PartnerPersonId { get; set; }
        public Nullable<int> ConsultPersonId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VKR_Themes_NPR> VKR_Themes_NPR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VKR_Themes_StudyPlans> VKR_Themes_StudyPlans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VKR_Themes_OrderNums> VKR_Themes_OrderNums { get; set; }
    }
}
