//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployerPartners.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class VKR_Themes_OrderNums
    {
        public int Id { get; set; }
        public int VKRThemeId { get; set; }
        public string OrderNum { get; set; }
        public System.DateTime OrderDate { get; set; }
    
        public virtual VKR_Themes VKR_Themes { get; set; }
    }
}
