//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployerPartners.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class VKR_ThemesAspirant_Review_PartnerPerson
    {
        public int Id { get; set; }
        public int VKR_ThemesAspirantOrderId { get; set; }
        public Nullable<int> PartnerPersonId { get; set; }
        public string Degree { get; set; }
        public string Rank { get; set; }
        public string Account { get; set; }
        public string Subdivision { get; set; }
        public string OrgPosition { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string SecondName { get; set; }
    }
}
