//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployerPartners.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkData
    {
        public int Id { get; set; }
        public string SystemUser { get; set; }
        public Nullable<int> OrgId { get; set; }
        public Nullable<int> PPId { get; set; }
        public Nullable<int> OrgStatRubricId { get; set; }
        public Nullable<int> OrgStatFacultyId { get; set; }
        public Nullable<int> OrgStatOwnershipTypeId { get; set; }
        public Nullable<int> OrgStatActivityGoalId { get; set; }
        public Nullable<int> OrgStatNationalAffiliationId { get; set; }
        public Nullable<int> OrgStatActivityAreaId { get; set; }
        public string OrgStatOrgListHeader { get; set; }
        public string OrgStatOrgListSDS { get; set; }
        public Nullable<int> OrgStatCountryId { get; set; }
        public Nullable<int> OrgStatRegionId { get; set; }
        public Nullable<int> PPStatRubricId { get; set; }
        public Nullable<int> PPStatFacultyId { get; set; }
        public Nullable<int> PPStatDegreeId { get; set; }
        public Nullable<int> PPStatRankId { get; set; }
        public Nullable<int> PPStatActivityAreaId { get; set; }
        public Nullable<int> PPStatCountryId { get; set; }
        public Nullable<int> PPStatRegionId { get; set; }
        public string PPStatPPListHeader { get; set; }
        public string PPStatPPListSDS { get; set; }
    }
}
