//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployerPartners
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployerContactDetails_GAK2016
    {
        public string SPbGU { get; set; }
        public string Chairman { get; set; }
        public string Title { get; set; }
        public string Name { get; set; }
        public string FirstNameEng { get; set; }
        public string LastNameEng { get; set; }
        public string Position { get; set; }
        public string PositionEng { get; set; }
        public string AAP { get; set; }
        public string AAPEng { get; set; }
        public string OrgName { get; set; }
        public string OrgNameEng { get; set; }
        public string CountryName { get; set; }
        public string CountryNameEng { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public int Id { get; set; }
    }
}
