//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployerPartners
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPLog
    {
        public int Id { get; set; }
        public string ActionName { get; set; }
        public string ActionValue { get; set; }
        public Nullable<System.DateTime> ActionTime { get; set; }
        public string ActionUser { get; set; }
        public string ActionName1 { get; set; }
        public string ActionValue1 { get; set; }
        public Nullable<System.DateTime> ActionTime1 { get; set; }
    }
}
