//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployerPartners
{
    using System;
    using System.Collections.Generic;
    
    public partial class GAK_StatChairmanPPNPR_Itog
    {
        public int StudyLevelId { get; set; }
        public string StudyLevel { get; set; }
        public Nullable<int> MemberExamSPbGU { get; set; }
        public Nullable<int> MemberExamPP { get; set; }
        public Nullable<int> MemberExamChairman { get; set; }
        public Nullable<int> MemberVKRSPbGU { get; set; }
        public Nullable<int> MemberVKRPP { get; set; }
        public Nullable<int> MemberVKRChairman { get; set; }
        public Nullable<int> MemberItogSPbGU { get; set; }
        public Nullable<int> MemberItogPP { get; set; }
        public Nullable<int> MemberItogChairman { get; set; }
    }
}
