//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployerPartners
{
    using System;
    using System.Collections.Generic;
    
    public partial class GAK_StatOP_Itog
    {
        public int StudyLevelId { get; set; }
        public string StudyLevel { get; set; }
        public Nullable<int> OPquan { get; set; }
        public Nullable<int> GAKquan { get; set; }
        public Nullable<int> GAKExamquan { get; set; }
        public Nullable<int> GAKVKRquan { get; set; }
        public Nullable<int> GAKItogquan { get; set; }
    }
}
