//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployerPartners
{
    using System;
    using System.Collections.Generic;
    
    public partial class GAK_Number
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GAK_Number()
        {
            this.GAK_Member = new HashSet<GAK_Member>();
            this.GAK_MemberNPR = new HashSet<GAK_MemberNPR>();
            this.GAK_MemberPP = new HashSet<GAK_MemberPP>();
            this.GAK_Number_log = new HashSet<GAK_Number_log>();
            this.GAK_Number_archive = new HashSet<GAK_Number_archive>();
        }
    
        public int Id { get; set; }
        public int GAKId { get; set; }
        public int ObrazProgramId { get; set; }
        public string GAKNumber { get; set; }
        public int ExamVKRId { get; set; }
        public Nullable<int> GAK_LP_PersonId { get; set; }
        public Nullable<int> PartnerPersonId { get; set; }
        public string Comment { get; set; }
        public string AuthorUpdated { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public string Author { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string Coordinator { get; set; }
        public string Address { get; set; }
        public string Auditorium { get; set; }
        public Nullable<System.DateTime> DateTimeMeeting { get; set; }
        public string GAKNumberOld { get; set; }
        public Nullable<bool> Freeze { get; set; }
        public Nullable<bool> ToOrder { get; set; }
        public Nullable<bool> InOrder { get; set; }
        public string OrderNumber { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<bool> OrderDop { get; set; }
    
        public virtual GAK GAK { get; set; }
        public virtual GAK_ExamVKR GAK_ExamVKR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GAK_Member> GAK_Member { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GAK_MemberNPR> GAK_MemberNPR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GAK_MemberPP> GAK_MemberPP { get; set; }
        public virtual PartnerPerson PartnerPerson { get; set; }
        public virtual ObrazProgram ObrazProgram { get; set; }
        public virtual GAK_LP_Person GAK_LP_Person { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GAK_Number_log> GAK_Number_log { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GAK_Number_archive> GAK_Number_archive { get; set; }
    }
}
