//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployerPartners
{
    using System;
    using System.Collections.Generic;
    
    public partial class GAK_StatOP
    {
        public int GAK_NumberId { get; set; }
        public string StudyLevel { get; set; }
        public int ExamVKRId { get; set; }
        public string ExamVKR { get; set; }
        public int ObrazProgramId { get; set; }
        public int StudyLevelId { get; set; }
    }
}
