//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployerPartners
{
    using System;
    using System.Collections.Generic;
    
    public partial class InboxMessageFile
    {
        public int Id { get; set; }
        public int InboxMessageId { get; set; }
        public byte[] FileData { get; set; }
        public string FileName { get; set; }
    
        public virtual InboxMessage InboxMessage { get; set; }
    }
}
