//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployerPartners
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObrazProgram
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ObrazProgram()
        {
            this.PracticeLPOP = new HashSet<PracticeLPOP>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string NameEng { get; set; }
        public string Acronym { get; set; }
        public string PrintName { get; set; }
        public string Number { get; set; }
        public int LicenseProgramId { get; set; }
        public int FacultyId { get; set; }
        public string OrderStart { get; set; }
        public string OrderClose { get; set; }
        public Nullable<int> SpecialistId { get; set; }
        public Nullable<int> ProgramStatusId { get; set; }
        public int ProgramModeId { get; set; }
        public string Agreement { get; set; }
        public Nullable<int> MobilityTypeId { get; set; }
        public bool IsExpress { get; set; }
        public bool IsOpen { get; set; }
        public string Holder { get; set; }
        public bool IsUseEng { get; set; }
        public string AdditionalInfo { get; set; }
        public double HoursForCredit { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateUpdate { get; set; }
        public string Author { get; set; }
    
        public virtual Faculty Faculty { get; set; }
        public virtual LicenseProgram LicenseProgram { get; set; }
        public virtual MobilityType MobilityType { get; set; }
        public virtual ProgramMode ProgramMode { get; set; }
        public virtual ProgramStatus ProgramStatus { get; set; }
        public virtual Specialist Specialist { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PracticeLPOP> PracticeLPOP { get; set; }
    }
}
