//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployerPartners
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObrazProgramInYear
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ObrazProgramInYear()
        {
            this.PracticeLPOP = new HashSet<PracticeLPOP>();
            this.VKROP = new HashSet<VKROP>();
        }
    
        public int Id { get; set; }
        public System.Guid ObrazProgramInYearId { get; set; }
        public int ObrazProgramId { get; set; }
        public int YearId { get; set; }
        public string Year { get; set; }
        public int LicenseProgramId { get; set; }
        public Nullable<int> SecondLicenseProgramId { get; set; }
        public string Name { get; set; }
        public string Number { get; set; }
        public string ObrazProgramCrypt { get; set; }
        public string StudyLevelName { get; set; }
        public int FacultyId { get; set; }
    
        public virtual Faculty Faculty { get; set; }
        public virtual LicenseProgram LicenseProgram { get; set; }
        public virtual ObrazProgram ObrazProgram { get; set; }
        public virtual Year Year1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PracticeLPOP> PracticeLPOP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VKROP> VKROP { get; set; }
    }
}
