//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployerPartners
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrganizationLP
    {
        public int Id { get; set; }
        public int OrganizationId { get; set; }
        public int LicenseProgramId { get; set; }
        public string Author { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual LicenseProgram LicenseProgram { get; set; }
        public virtual Organization Organization { get; set; }
    }
}
