//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployerPartners
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrganizationOkved
    {
        public int Id { get; set; }
        public int OrganizationId { get; set; }
        public string Okved { get; set; }
        public int OkvedTypeId { get; set; }
        public string OkvedName { get; set; }
        public string Author { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    
        public virtual OkvedType OkvedType { get; set; }
        public virtual Organization Organization { get; set; }
    }
}
