//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployerPartners
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnerPersonFaculty
    {
        public int Id { get; set; }
        public int PartnerPersonId { get; set; }
        public int FacultyId { get; set; }
        public string Author { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual Faculty Faculty { get; set; }
        public virtual PartnerPerson PartnerPerson { get; set; }
    }
}
