//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployerPartners
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnerPerson
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PartnerPerson()
        {
            this.OrganizationPerson = new HashSet<OrganizationPerson>();
            this.PartnerPersonActivityArea = new HashSet<PartnerPersonActivityArea>();
            this.PartnerPersonFaculty = new HashSet<PartnerPersonFaculty>();
            this.PartnerPersonLP = new HashSet<PartnerPersonLP>();
            this.PartnerPersonRubric = new HashSet<PartnerPersonRubric>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string NameEng { get; set; }
        public string Title { get; set; }
        public Nullable<int> DegreeId { get; set; }
        public Nullable<int> RankId { get; set; }
        public Nullable<int> ActivityAreaId { get; set; }
        public Nullable<bool> IsSPbGUGraduate { get; set; }
        public Nullable<int> SPbGUGraduateYear { get; set; }
        public Nullable<bool> AlumniAssociation { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Mobiles { get; set; }
        public string WebSite { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> RegionId { get; set; }
        public string CodeKLADR { get; set; }
        public string Code { get; set; }
        public string City { get; set; }
        public string Street { get; set; }
        public string House { get; set; }
        public string Comment { get; set; }
        public string Author { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.Guid rowguid { get; set; }
    
        public virtual ActivityArea ActivityArea { get; set; }
        public virtual Country Country { get; set; }
        public virtual Degree Degree { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrganizationPerson> OrganizationPerson { get; set; }
        public virtual Rank Rank { get; set; }
        public virtual Region Region { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartnerPersonActivityArea> PartnerPersonActivityArea { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartnerPersonFaculty> PartnerPersonFaculty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartnerPersonLP> PartnerPersonLP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartnerPersonRubric> PartnerPersonRubric { get; set; }
    }
}
