//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployerPartners
{
    using System;
    using System.Collections.Generic;
    
    public partial class PracticeLP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PracticeLP()
        {
            this.PracticeLPOrganization = new HashSet<PracticeLPOrganization>();
            this.PracticeLPStudent = new HashSet<PracticeLPStudent>();
            this.PracticeLPFile = new HashSet<PracticeLPFile>();
            this.PracticeLPOP = new HashSet<PracticeLPOP>();
        }
    
        public int Id { get; set; }
        public int PracticeId { get; set; }
        public int LicenseProgramId { get; set; }
        public Nullable<int> PracticeTypeId { get; set; }
        public Nullable<System.DateTime> DateStart { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public string OrderDoc { get; set; }
        public string OrderNumber { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string OrderAuthor { get; set; }
        public string InstructionDoc { get; set; }
        public string InstructionNumber { get; set; }
        public Nullable<System.DateTime> InstructionDate { get; set; }
        public string InstructionAuthor { get; set; }
        public string Supervisor { get; set; }
        public string AdvanceHolder { get; set; }
        public string Comment { get; set; }
        public string Author { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<bool> OutSPb { get; set; }
    
        public virtual LicenseProgram LicenseProgram { get; set; }
        public virtual Practice Practice { get; set; }
        public virtual PracticeType PracticeType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PracticeLPOrganization> PracticeLPOrganization { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PracticeLPStudent> PracticeLPStudent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PracticeLPFile> PracticeLPFile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PracticeLPOP> PracticeLPOP { get; set; }
    }
}
