//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployerPartners
{
    using System;
    using System.Collections.Generic;
    
    public partial class PracticeStudent
    {
        public int Id { get; set; }
        public int PracticeId { get; set; }
        public int StudentId { get; set; }
        public Nullable<int> OrganizationId { get; set; }
        public Nullable<int> PracticeLPOrganizationId { get; set; }
        public string Comment { get; set; }
        public string Author { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string StudentFIO { get; set; }
    
        public virtual Organization Organization { get; set; }
        public virtual Practice Practice { get; set; }
        public virtual PracticeLPOrganization PracticeLPOrganization { get; set; }
        public virtual Student Student { get; set; }
    }
}
