//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployerPartners
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAP_ALL_PERS
    {
        public string Persnum { get; set; }
        public string Tabnum { get; set; }
        public string Lastname { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Birthdate { get; set; }
        public string Positionname { get; set; }
        public string OrgId { get; set; }
        public string OrgUpId { get; set; }
        public string ShortName { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public string UsridAd { get; set; }
        public string Pkateg { get; set; }
        public string Pgroup { get; set; }
        public string Telnr { get; set; }
        public string Addressfact { get; set; }
        public string Titel { get; set; }
        public string Titl2 { get; set; }
        public string Civil { get; set; }
        public Nullable<System.DateTime> TIMESTAMP { get; set; }
    }
}
