//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployerPartners
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAP_POSITIONS
    {
        public string PosId { get; set; }
        public string OrgId { get; set; }
        public string Name { get; set; }
        public string FullName { get; set; }
        public string DateFrom { get; set; }
        public string DateTo { get; set; }
        public string Quantity { get; set; }
        public Nullable<System.DateTime> TIMESTAMP { get; set; }
    }
}
