//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployerPartners
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAP_ORGSTRUCTURE
    {
        public string OrgId { get; set; }
        public string OrgUpId { get; set; }
        public string ShortName { get; set; }
        public string FullName { get; set; }
        public string Begda { get; set; }
        public string Endda { get; set; }
        public Nullable<System.DateTime> TIMESTAMP { get; set; }
    }
}
