//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployerPartners
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentDVZ
    {
        public int Id { get; set; }
        public Nullable<int> StudDataId { get; set; }
        public string FIO { get; set; }
        public string Surname { get; set; }
        public string FirstName { get; set; }
        public string SecondName { get; set; }
        public string Course { get; set; }
        public string WorkPlan { get; set; }
        public string RegNomWP { get; set; }
        public string Department { get; set; }
        public string StudyBasis { get; set; }
        public string DegreeName { get; set; }
        public string Accout { get; set; }
        public string MailBox { get; set; }
        public string FacultyName { get; set; }
        public string DR { get; set; }
        public string PersNumber { get; set; }
        public string SpecNumber { get; set; }
        public string SpecName { get; set; }
        public string StatusName { get; set; }
        public string StudyingName { get; set; }
    }
}
