//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployerPartners
{
    using System;
    using System.Collections.Generic;
    
    public partial class VKR_Themes
    {
        public int Id { get; set; }
        public string GraduateYear { get; set; }
        public string VKRSourceKey { get; set; }
        public string DocumentNumber { get; set; }
        public string NPR_LastName { get; set; }
        public string NPR_FirstName { get; set; }
        public string NPR_SecondName { get; set; }
        public string NPR_Position { get; set; }
        public string NPR_Degree { get; set; }
        public string NPR_Rank { get; set; }
        public string NPR_Account { get; set; }
        public string NPR_Chair { get; set; }
        public string NPR_Faculty { get; set; }
        public string VKRName { get; set; }
        public string VKRNameEng { get; set; }
        public Nullable<int> LicenseProgramId { get; set; }
        public string LicenseProgramName { get; set; }
        public string LicenseProgramCode { get; set; }
        public string Crypt { get; set; }
        public string StudyPlanNum { get; set; }
        public Nullable<int> ObrazProgramId { get; set; }
        public string ObrazProgramName { get; set; }
        public Nullable<int> OrganizationId { get; set; }
        public string OrganizationName { get; set; }
        public string Student_LastName { get; set; }
        public string Student_FirstName { get; set; }
        public string Student_SecondName { get; set; }
        public string Student_Account { get; set; }
        public string Consult_LastName { get; set; }
        public string Consult_FirstName { get; set; }
        public string Consult_SecondName { get; set; }
        public string Consult_Position { get; set; }
        public string Consult_Degree { get; set; }
        public string Consult_Rank { get; set; }
        public Nullable<int> Consult_OrganizationId { get; set; }
        public string Consult_OrganizationName { get; set; }
        public string Student_Agreed_LastName { get; set; }
        public string Student_Agreed_FirstName { get; set; }
        public string Student_Agreed_SecondName { get; set; }
        public string Student_Agreed_Account { get; set; }
        public string Comment { get; set; }
        public string Author { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<bool> InOrder { get; set; }
        public string OrderNumber { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
    }
}
