//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployerPartners
{
    using System;
    using System.Collections.Generic;
    
    public partial class VKROPTheme
    {
        public int Id { get; set; }
        public int VKROPId { get; set; }
        public int OrganizationId { get; set; }
        public Nullable<int> OrganizationAgreedId { get; set; }
        public Nullable<int> VKRCoordinatorId { get; set; }
        public string VKRName { get; set; }
        public string VKRNameEng { get; set; }
        public string Comment { get; set; }
        public string Author { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    
        public virtual Organization Organization { get; set; }
        public virtual Organization Organization1 { get; set; }
        public virtual VKRCoordinator VKRCoordinator { get; set; }
        public virtual VKROP VKROP { get; set; }
    }
}
