//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployerPartners
{
    using System;
    using System.Collections.Generic;
    
    public partial class VKROP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VKROP()
        {
            this.VKROPTheme = new HashSet<VKROPTheme>();
            this.VKROPStudent = new HashSet<VKROPStudent>();
        }
    
        public int Id { get; set; }
        public int VKRId { get; set; }
        public int ObrazProgramId { get; set; }
        public int ObrazProgramInYearId { get; set; }
        public Nullable<int> VKRCoordinatorId { get; set; }
        public string Comment { get; set; }
        public string Author { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    
        public virtual ObrazProgram ObrazProgram { get; set; }
        public virtual ObrazProgramInYear ObrazProgramInYear { get; set; }
        public virtual VKR VKR { get; set; }
        public virtual VKRCoordinator VKRCoordinator { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VKROPTheme> VKROPTheme { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VKROPStudent> VKROPStudent { get; set; }
    }
}
