//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployerPartners
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkData
    {
        public int Id { get; set; }
        public string SystemUser { get; set; }
        public Nullable<int> OrgId { get; set; }
        public Nullable<int> PPId { get; set; }
        public Nullable<int> FacultyId { get; set; }
        public Nullable<int> UMKId { get; set; }
        public Nullable<int> SOPId { get; set; }
        public Nullable<int> VKRYear { get; set; }
        public Nullable<int> PracticeId { get; set; }
        public Nullable<int> PracticeLPId { get; set; }
        public Nullable<int> GAKId { get; set; }
        public Nullable<int> GAKLPId { get; set; }
        public Nullable<int> Rep_LicenseProgramId { get; set; }
        public Nullable<int> Rep_VKRLicenseProgramId { get; set; }
        public string Okved { get; set; }
        public Nullable<int> OwnershipTypeId { get; set; }
        public Nullable<int> ActivityGoalId { get; set; }
        public Nullable<int> NationalAffiliationId { get; set; }
        public Nullable<int> CountryId { get; set; }
    }
}
